def NATO(w):
    words = {
            "a":"alfa",
            "b":"bravo",
            "c":"charlie",
            "d":"delta",
            "e":"echo",
            "f":"foxtrot",
            "g":"golf",
            "h":"hotel",
            "i":"india",
            "j":"juliett",
            "k":"kilo",
            "l":"lima",
            "m":"mike",
            "n":"november",
            "o":"oscar",
            "p":"papa",
            "q":"quebec",
            "r":"romeo",
            "s":"sierra",
            "t":"tango",
            "u":"uniform",
            "v":"victor",
            "w":"whiskey",
            "x":"x-ray",
            "y":"yankee",
            "z":"zulu",
            
            "A":"Alfa",
            "B":"Bravo",
            "C":"Charlie",
            "D":"Delta",
            "E":"Echo",
            "F":"Foxtrot",
            "G":"Golf",
            "H":"Hotel",
            "I":"India",
            "J":"Juliett",
            "K":"Kilo",
            "L":"Lima",
            "M":"Mike",
            "N":"November",
            "O":"Oscar",
            "P":"Papa",
            "Q":"Quebec",
            "R":"Romeo",
            "S":"Sierra",
            "T":"Tango",
            "U":"Uniform",
            "V":"Victor",
            "W":"Whiskey",
            "X":"X-ray",
            "Y":"Yankee",
            "Z":"Zulu",
            " ":" "
        }

    for i in range(len(w)):
        print(words[w[i]] + " ")
